// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_7fIHc0NPBoLJleKRRX8ZT5O-oJ08Jmk',
    appId: '1:7714332286:web:c7fa33c7374eddc5ee822f',
    messagingSenderId: '7714332286',
    projectId: 'pd-app-49375',
    authDomain: 'pd-app-49375.firebaseapp.com',
    storageBucket: 'pd-app-49375.appspot.com',
    measurementId: 'G-J9Y7YBRDTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTGksqkgzcoqwEm-_YLoxxqUSp99AWg_s',
    appId: '1:7714332286:android:35337c701f4fc9f9ee822f',
    messagingSenderId: '7714332286',
    projectId: 'pd-app-49375',
    storageBucket: 'pd-app-49375.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3fl2iTHSXMgJ4Z65ts13XC8tdUgyLpo',
    appId: '1:7714332286:ios:62e4a5ab5f2c1e40ee822f',
    messagingSenderId: '7714332286',
    projectId: 'pd-app-49375',
    storageBucket: 'pd-app-49375.appspot.com',
    iosClientId: '7714332286-hq4f725fr7vqk4eb1umob4qo4rj58eak.apps.googleusercontent.com',
    iosBundleId: 'com.example.pdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf3fl2iTHSXMgJ4Z65ts13XC8tdUgyLpo',
    appId: '1:7714332286:ios:afedb02f48869159ee822f',
    messagingSenderId: '7714332286',
    projectId: 'pd-app-49375',
    storageBucket: 'pd-app-49375.appspot.com',
    iosClientId: '7714332286-qgnk0gqeab37pj8qpkjut26jf78t464p.apps.googleusercontent.com',
    iosBundleId: 'com.ntu.pdApp',
  );
}
